CREATE DATABASE proyectosql;
USE proyectosql;
/*------------------------------------------------Creacion de tablas------------------------------------------------*/
CREATE TABLE ROLES(
    ID_ROL_PK INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_ROL VARCHAR(100) NOT NULL
);
CREATE TABLE ESTADOS(
    ID_ESTADO_PK INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_ESTADO VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(1024) NOT NULL
);
CREATE TABLE CATEGORIAS(
    ID_CATEGORIA_PK INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CATEGORIA VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(1024) NOT NULL
);

CREATE TABLE PROFESIONES(
	ID_PROFESION_PK INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PROFESION VARCHAR(100)
);

CREATE TABLE USUARIOS(
    ID_USUARIO_PK INT PRIMARY KEY AUTO_INCREMENT,
    ID_ROL_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL DEFAULT 1, /*EL DEFAULT 1 ES PARA DECIR QUE EL ID DEL ESTADO SERA 1 PREDETERMINADAMENTE PARA NO TENER QUE INSERTARLO EN LO VISUAL*/
    ID_PROFESION_FK INT NOT NULL,
    CEDULA_USUARIO INT NOT NULL,
    NOMBRE_USUARIO VARCHAR(100) NOT NULL,
    APELLIDO1 VARCHAR(100) NOT NULL,
    APELLIDO2 VARCHAR(100) NOT NULL,
    EDAD INT NOT NULL,
    DIRECCION VARCHAR(300),
    TELEFONO VARCHAR(100),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(100) NOT NULL,
    FACEBOOK VARCHAR(200),
    INSTAGRAM VARCHAR(200),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IMAGEN_URL VARCHAR(300),
    /*POSIBLEMENTE A CAMBIAR*/
    FOREIGN KEY (ID_ROL_FK) REFERENCES ROLES(ID_ROL_PK),
    FOREIGN KEY (ID_ESTADO_FK) REFERENCES ESTADOS(ID_ESTADO_PK),
    FOREIGN KEY (ID_PROFESION_FK) REFERENCES PROFESIONES(ID_PROFESION_PK)
);
CREATE TABLE CALIFICACION (
    ID_CALIFICACION_PK INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO_FK INT NOT NULL,
    PUNTUACION INT
);
CREATE TABLE PUBLICACIONES(
    ID_PUBLICACION_PK INT PRIMARY KEY AUTO_INCREMENT,
    ID_ESTADO_FK INT NOT NULL DEFAULT 1, /*EL DEFAULT 1 ES PARA DECIR QUE EL ID DEL ESTADO SERA 1 PREDETERMINADAMENTE PARA NO TENER QUE INSERTARLO EN LO VISUAL*/
    ID_CATEGORIA_FK INT NOT NULL,
    ID_CALIFICACION_FK INT,
    TITULO_PUBLICACION VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(1024) NOT NULL,
    FECHA_PUBLICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    /*AGREGAR IMAGEN QUEDA PENDIENTE*/
    ID_USUARIO_FK INT NOT NULL,
    UBICACION VARCHAR(500) NOT NULL,
    PRECIO_APROX DOUBLE NOT NULL,
    FOREIGN KEY (ID_USUARIO_FK) REFERENCES USUARIOS(ID_USUARIO_PK),
    FOREIGN KEY (ID_CALIFICACION_FK) REFERENCES CALIFICACION(ID_CALIFICACION_PK),
    FOREIGN KEY (ID_CATEGORIA_FK) REFERENCES CATEGORIAS(ID_CATEGORIA_PK),
    FOREIGN KEY (ID_ESTADO_FK) REFERENCES ESTADOS(ID_ESTADO_PK)
);

/*------------------------------------------------INSERT DE PRUEBA------------------------------------------------*/
INSERT INTO ROLES(NOMBRE_ROL) VALUES('ADMIN');
INSERT INTO ROLES(NOMBRE_ROL) VALUES('POSTULANTE');
INSERT INTO ROLES(NOMBRE_ROL) VALUES('RECLUTADOR');

SELECT * FROM ROLES;

INSERT INTO ESTADOS(NOMBRE_ESTADO, DESCRIPCION) VALUES('ACTIVO', 'Dato activo');
INSERT INTO ESTADOS(NOMBRE_ESTADO, DESCRIPCION) VALUES('INACTIVO', 'Dato inactivo');

INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('CUIDADO-NINOS', 'Servicios de Cuidado de Niños');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('JARDINERIA', 'Servicios de Jardinería');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('ARREGLO-ROPA', 'Servicios de Arreglos de Ropa');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('LIMPIEZA', 'Servicios de Limpieza');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('CUIDADO-MASCOTAS', 'Servicios de Cuidado de Mascotas');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('REPARACIONES', 'Servicios de Reparaciones y Mantenimiento');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('COMIDA-CATERING', 'Servicios de Comida y Catering');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('VENTAS', 'Servicios de Ventas');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('ASISTENCIA-PERSONAL', 'Servicios de Asistencia Personal');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('BELLEZA', 'Servicios de Belleza');
INSERT INTO CATEGORIAS(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('OTROS-EMPLEADOS', 'Otros Empleos');

-- INSERT DE PROFESIONES
INSERT INTO PROFESIONES(NOMBRE_PROFESION) VALUES('Especialista en tecnología');
INSERT INTO PROFESIONES(NOMBRE_PROFESION) VALUES('Ingeniero');
INSERT INTO PROFESIONES(NOMBRE_PROFESION) VALUES('Profesional de la salud');
INSERT INTO PROFESIONES(NOMBRE_PROFESION) VALUES('Operador de transporte');

select * from PROFESIONES;

-- Insert 1
INSERT INTO USUARIOS(ID_ROL_FK, ID_PROFESION_FK, CEDULA_USUARIO, NOMBRE_USUARIO, APELLIDO1, APELLIDO2, EDAD, DIRECCION, TELEFONO, EMAIL, CONTRASENA) 
VALUES (1, 1,'123456789', 'Brandon', 'Aguirre', 'Ortiz', 19, 'Calle Ficticia 123', '987654321', 'test', 'test');

-- Insert 1
INSERT INTO USUARIOS(ID_ROL_FK, ID_PROFESION_FK,CEDULA_USUARIO, NOMBRE_USUARIO, APELLIDO1, APELLIDO2, EDAD, DIRECCION, TELEFONO, EMAIL, CONTRASENA) 
VALUES (1, 1,'123456789', 'Juan', 'Perez', 'Lopez', 30, 'Calle Ficticia 123', '987654321', 'juan.perez@example.com', 'password');

-- Insert 2
INSERT INTO USUARIOS(ID_ROL_FK, ID_PROFESION_FK,CEDULA_USUARIO, NOMBRE_USUARIO, APELLIDO1, APELLIDO2, EDAD, DIRECCION, TELEFONO, EMAIL, CONTRASENA) 
VALUES (2, 2,'987654321','Maria', 'Gomez', 'Sanchez', 28, 'Avenida Central 456', '654987123', 'maria.gomez@example.com', 'password');

-- Insert 3
INSERT INTO USUARIOS(ID_ROL_FK, ID_PROFESION_FK,CEDULA_USUARIO, NOMBRE_USUARIO, APELLIDO1, APELLIDO2, EDAD, DIRECCION, TELEFONO, EMAIL, CONTRASENA) 
VALUES (3, 4,'456789123','Carlos', 'Martinez', 'Ramirez', 35, 'Calle Real 789', '321654987', 'carlos.martinez@example.com', 'password');

-- Insert Publicaciones
INSERT INTO PUBLICACIONES(ID_ESTADO_FK, ID_CATEGORIA_FK, TITULO_PUBLICACION, DESCRIPCION, ID_USUARIO_FK, UBICACION, PRECIO_APROX) 
VALUES (1, 1, 'Venta de Ropa de Segunda Mano', 'Descripcion de la publicacion', 1, 'Calle Real 789', 100.00);

INSERT INTO PUBLICACIONES(ID_ESTADO_FK, ID_CATEGORIA_FK, TITULO_PUBLICACION, DESCRIPCION, ID_USUARIO_FK, UBICACION, PRECIO_APROX) 
VALUES (1, 2, 'Servicios de Arreglos Florales', 'Descripcion de la publicacion', 1, 'Calle Real 789', 100.00);

INSERT INTO PUBLICACIONES(ID_ESTADO_FK, ID_CATEGORIA_FK, TITULO_PUBLICACION, DESCRIPCION, ID_USUARIO_FK, UBICACION, PRECIO_APROX)
VALUES (1, 3, 'Servicios de Arreglos Florales', 'Descripcion de la publicacion', 1, 'Calle Real 789', 100.00);

INSERT INTO PUBLICACIONES(ID_ESTADO_FK, ID_CATEGORIA_FK, TITULO_PUBLICACION, DESCRIPCION, ID_USUARIO_FK, UBICACION, PRECIO_APROX) 
VALUES (1, 4, 'Servicios de Arreglos Florales', 'Descripcion de la publicacion', 1, 'Calle Real 789', 100.00);

SELECT * FROM USUARIOS;